**Українська версія:**

Дослідницький Аналіз Даних (EDA)

У цьому ноутбуці проводиться дослідницький аналіз даних клієнтів телекомунікаційної компанії з метою розуміння основних закономірностей та характеристик набору даних перед побудовою моделі прогнозування відтоку.

Завдання:

1. Вивчення розподілів ключових ознак (демографічні дані, тривалість користування послугами, тарифи, тип контракту тощо)
2. Виявлення відсутніх значень та оцінка їхнього впливу на набір даних
3. Аналіз кореляцій між ознаками та цільовою змінною (Churn)
4. Виявлення потенційних викидів та проблем якості даних, які потребуватимуть уваги на етапі попередньої обробки

Висновки, отримані на цьому етапі, безпосередньо визначатимуть кроки попередньої обробки даних на наступному етапі проєкту.

**English version:**

Exploratory Data Analysis (EDA)

This notebook performs exploratory data analysis on the telecom customer dataset to understand the underlying patterns and characteristics before building a churn prediction model.

Goals:

1. Explore the distribution of key features (demographics, tenure, charges, contract types, etc.)
2. Identify missing values and assess their impact on the dataset
3. Analyze correlations between features and the target variable (Churn)
4. Detect potential outliers and data quality issues that may require attention during preprocessing

The insights gathered here will directly inform the preprocessing steps in the next stage of the project.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [4]:
df = pd.read_csv('../data/raw/internet_service_churn.csv')

In [5]:
df.head(10)

,id,is_tv_subscriber,is_movie_package_subscriber,subscription_age,bill_avg,reamining_contract,service_failure_count,download_avg,upload_avg,download_over_limit,churn
0,15,1,0,11.95,25,0.14,0,8.4,2.3,0,0
1,18,0,0,8.22,0,NaN,0,0.0,0.0,0,1
2,23,1,0,8.91,16,0.00,0,13.7,0.9,0,1
3,27,0,0,6.87,21,NaN,1,0.0,0.0,0,1
4,34,0,0,6.39,0,NaN,0,0.0,0.0,0,1
5,56,1,1,11.94,32,1.38,0,69.4,4.0,0,0
6,71,0,0,8.96,18,0.00,0,21.3,2.0,0,1
7,84,0,0,5.48,14,NaN,1,0.0,0.0,0,1
8,94,0,0,8.54,0,NaN,0,0.0,0.0,0,1
9,112,0,0,8.33,0,NaN,0,0.0,0.0,0,1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72274 entries, 0 to 72273
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           72274 non-null  int64
 1   is_tv_subscriber             72274 non-null  int64
 2   is_movie_package_subscriber  72274 non-null  int64
 3   subscription_age             72274 non-null  float64
 4   bill_avg                     72274 non-null  int64
 5   reamining_contract           50702 non-null  float64
 6   service_failure_count        72274 non-null  int64
 7   download_avg                 71893 non-null  float64
 8   upload_avg                   71893 non-null  float64
 9   download_over_limit          72274 non-null  int64
 10  churn                        72274 non-null  int64
dtypes: float64(4), int64(7)
memory usage: 6.1 MB

In [7]:
df.describe()

,id,is_tv_subscriber,is_movie_package_subscriber,subscription_age,bill_avg,reamining_contract,service_failure_count,download_avg,upload_avg,download_over_limit,churn
count,7.227400e+04,72274.000000,72274.000000,72274.000000,72274.000000,50702.000000,72274.000000,71893.000000,71893.000000,72274.000000,72274.000000
mean,8.463182e+05,0.815259,0.334629,2.450051,18.942483,0.716039,0.274234,43.689911,4.192076,0.207613,0.554141
std,4.891022e+05,0.388090,0.471864,2.034990,13.215386,0.697102,0.816621,63.405963,9.818896,0.997123,0.497064
min,1.500000e+01,0.000000,0.000000,-0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.222165e+05,1.000000,0.000000,0.930000,13.000000,0.000000,0.000000,6.700000,0.500000,0.000000,0.000000
50%,8.477840e+05,1.000000,0.000000,1.980000,19.000000,0.570000,0.000000,27.800000,2.100000,0.000000,1.000000
75%,1.269562e+06,1.000000,1.000000,3.300000,22.000000,1.310000,0.000000,60.500000,4.800000,0.000000,1.000000
max,1.689744e+06,1.000000,1.000000,12.800000,406.000000,2.920000,19.000000,4415.200000,453.300000,7.000000,1.000000

In [14]:
duplications_amount = df.duplicated().sum()
if duplications_amount > 0:
    df = df.drop_duplicates()
    df
duplications_amount

0

In [12]:
df.head(15)

,id,is_tv_subscriber,is_movie_package_subscriber,subscription_age,bill_avg,reamining_contract,service_failure_count,download_avg,upload_avg,download_over_limit,churn
0,15,1,0,11.95,25,0.14,0,8.4,2.3,0,0
1,18,0,0,8.22,0,NaN,0,0.0,0.0,0,1
2,23,1,0,8.91,16,0.00,0,13.7,0.9,0,1
3,27,0,0,6.87,21,NaN,1,0.0,0.0,0,1
4,34,0,0,6.39,0,NaN,0,0.0,0.0,0,1
5,56,1,1,11.94,32,1.38,0,69.4,4.0,0,0
6,71,0,0,8.96,18,0.00,0,21.3,2.0,0,1
7,84,0,0,5.48,14,NaN,1,0.0,0.0,0,1
8,94,0,0,8.54,0,NaN,0,0.0,0.0,0,1
9,112,0,0,8.33,0,NaN,0,0.0,0.0,0,1
10,166,1,1,8.44,17,0.00,0,9.9,1.1,0,1
11,174,1,1,11.93,10,1.28,0,10.6,0.6,0,0
12,213,0,0,6.64,10,NaN,0,0.0,0.0,0,1
13,222,0,0,5.53,14,NaN,0,0.0,0.0,0,1
14,270,0,0,6.97,23,0.28,0,0.0,0.0,0,1

In [9]:
df['is_tv_subscriber'].value_counts()

is_tv_subscriber
1    58922
0    13352
Name: count, dtype: int64

In [15]:
df['is_movie_package_subscriber'].value_counts()

is_movie_package_subscriber
0    48089
1    24185
Name: count, dtype: int64

In [31]:
dual_subscription = ((df['is_tv_subscriber'] == 1) & (df['is_movie_package_subscriber'] == 1)).sum()
print('Користувачі, які мають подвійну підписку: ', dual_subscription)
# print('Users that have a dual subscription: ', dual_subscription)

Користувачі, які мають подвійну підписку:  24183